spring.application.name=LibertyTest
server.port = 9177

# H2 Database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-liberty

spring.datasource.url=jdbc:h2:mem:LibertyTest;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=manoj
spring.datasource.password=manoj1
#file updload
spring.servlet.multipart.max-file-size:64MB
spring.servlet.multipart.max-request-size:64MB
spring.image.upload-dir:C:/Angular_SpringBoot_H2/img
spring.jpa.show-sql=true


spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring security
#spring.security.user.name=manoj
#spring.security.user.password=manoj1
#JWT angular + postgrage + auth 0(token jwt)